### ISSUE TITLE
Error while sending frame: TXStatus.NWK_ROUTE_DISCOVERY_FAILED

### ISSUE THREAD

**Issue by seblu** [zigpy/zigpy-deconz#169]
The background context is a migration from a Raspberry Pi 4 **ZHA** setup with a **Raspbee2** radio to a **Conbee2** radio module. There is around 100 Zigbee devices paired.

The Raspbee2 zigbee parameters has been cloned to the Conbee2 via the Phoscon UI.
**MacAddress**, **TC Address**, **Network Key**, **TC Link Key**, **NWK Update ID** and **Channel Mask** are equals after cloning. 
I triple checked this via the zigpy-cli (nb. do not display the Network Key), debug output of homeassitant and Phoscon Restore/Backup JSON.

This is the JSON exported as backup for both keys:
```json
{
   "apsAck" : false,
   "apsUseExtPanId" : "0x0",
   "curChannel" : 15,
   "deconzVersion" : "21206",
   "deviceType" : 0,
   "endpoint1" : {
      "deviceId" : "0x5",
      "deviceVersion" : "0x1",
      "endpoint" : "0x1",
      "inClusters" : [
         "0x0",
         "0xa",
         "0x19",
         "0x501"
      ],
      "index" : 0,
      "outClusters" : [
         "0x1",
         "0x20",
         "0x500",
         "0x502"
      ],
      "profileId" : "0x104"
   },
   "endpoint2" : {
      "deviceId" : "0x64",
      "deviceVersion" : "0x1",
      "endpoint" : "0xf2",
      "inClusters" : [],
      "index" : 1,
      "outClusters" : [
         "0x21"
      ],
      "profileId" : "0xa1e0"
   },
   "extPanId" : "0x*****",
   "frameCounter" : "*****",
   "macAddress" : "0x*****",
   "networkKey" : "*****",
   "nwkAddress" : "0x*****",
   "nwkUpdateId" : "*****",
   "otauactive" : 0,
   "panId" : "0x*****",
   "securityMode" : 3,
   "staticNwkAddress" : false,
   "tcAddress" : "0x*****",
   "tcLinkKey" : "*****"
}
```

So both radio modules should be equal and there are threads[^1][^2][^3] about success stories with this method using the deconz plugin.

The Conbee2 path is `/dev/ttyACM0` while the Raspbee2 path is `/dev/ttyAMA0`, so after the path being adjusted in the `.storage/core.config_entries` and HomeAssistant restarted, I get these errors :

```
2021-10-21 15:33:04 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 31 under 32 request id, data: b'001f000240030004000700'
2021-10-21 15:33:04 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (26, 32, 0, <DeconzAddressEndpoint address_mode=2 address=0xFDAB endpoint=11>, 260, 768, 1, b'\x00\x1f\x00\x02@\x03\x00\x04\x00\x07\x00', 2, 0)
2021-10-21 15:33:04 DEBUG (MainThread) [zigpy_deconz.api] APS data request response: [2, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|2: 34>, 32]
2021-10-21 15:33:04 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 32: d0
2021-10-21 15:33:04 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x20 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0xfdab endpoint=11>, status: 0xd0
2021-10-21 15:33:04 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Error while sending 32 req id frame: TXStatus.NWK_ROUTE_DISCOVERY_FAILED
2021-10-21 15:33:04 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xFDAB:11:0x0300]: async_initialize: all attempts have failed: [DeliveryError('[0xfdab:11:0x0300]: Message send failure'), DeliveryError('[0xfdab:11:0x0300]: Message send failure'), DeliveryError('[0xfdab:11:0x0300]: Message send failure'), DeliveryError('[0xfdab:11:0x0300]: Message send failure')]
```

The **NWK_ROUTE_DISCOVERY_FAILED** is defined in https://github.com/zigpy/zigpy/blob/468b533eda9216dfc679acd6d542849206daa87d/zigpy/types/named.py#L474 and the comment says:
> An attempt to discover a route has failed due to a reason other than a lack of routing capacity

I'm a bit stuck by this error message as I don't know where to look next to fix a routing issue.

[^1]: https://community.home-assistant.io/t/deconz-please-help-rpi-raspbee-nuc-conbee/193111
[^2]: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2742
[^3]: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1441

**Comment by puddly** [comment]
This is likely too late to be helpful, but I had a similar issue with a Conbee II not actually accepting a frame counter write.  The migration seemingly "worked" but the frame counter was never actually updated, causing outgoing requests from the device to be rejected by routers on the network.

If you still have both devices and want to try this again, upgrade them both to the latest firmware and try migrating once more with https://github.com/zigpy/zigpy-cli/pull/2.  If your Conbee has the same bug as mine, in theory performing a backup with the Conbee still plugged in will yield nearly identical network settings to the Raspbee (+/- a few hundred for the frame counter), but unplugging it and plugging it back in will cause the frame counter to "reset" to its old value.

**Comment by claudegel** [comment]
Hi I have a similar problem with my Conbee II and ZHA. my log are floud with thos error:
Is it my Conbee that is going bad ?
```
2023-12-31 15:39:36.858 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:86 sequence
2023-12-31 15:39:36.878 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:88 sequence
2023-12-31 15:39:36.889 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 180, Status: TXStatus.SUCCESS
2023-12-31 15:39:36.951 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 182, Status: TXStatus.SUCCESS
2023-12-31 15:39:37.311 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:a3 sequence
2023-12-31 15:39:37.322 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:a4 sequence
2023-12-31 15:39:37.334 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:a5 sequence
2023-12-31 15:39:37.352 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:a7 sequence
2023-12-31 15:39:37.384 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:ac sequence
2023-12-31 15:39:37.465 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:b3 sequence
2023-12-31 15:39:37.482 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:b6 sequence
2023-12-31 15:39:37.556 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 200, Status: TXStatus.SUCCESS
2023-12-31 15:39:37.678 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 204, Status: TXStatus.SUCCESS
2023-12-31 15:39:37.701 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:ca sequence
2023-12-31 15:39:38.086 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:ce sequence
2023-12-31 15:39:38.095 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:cf sequence
2023-12-31 15:39:38.739 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:d5 sequence
2023-12-31 15:39:38.762 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:d9 sequence
2023-12-31 15:39:38.766 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 213, Status: TXStatus.SUCCESS
2023-12-31 15:39:38.790 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:de sequence
2023-12-31 15:39:38.943 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 218, Status: TXStatus.SUCCESS
2023-12-31 15:39:39.200 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:fd sequence
2023-12-31 15:39:40.243 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:05 sequence
2023-12-31 15:39:41.445 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:14 sequence
2023-12-31 15:39:41.467 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:16 sequence
2023-12-31 15:39:41.495 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 244, Status: TXStatus.SUCCESS
2023-12-31 15:39:41.514 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 244, Status: TXStatus.SUCCESS
2023-12-31 15:39:41.541 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 244, Status: TXStatus.SUCCESS
2023-12-31 15:39:41.623 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:20 sequence
2023-12-31 15:39:41.981 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 253, Status: TXStatus.MAC_NO_ACK
2023-12-31 15:39:41.990 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:33 sequence
2023-12-31 15:39:42.000 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 253, Status: TXStatus.SUCCESS
2023-12-31 15:39:42.042 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:39 sequence
2023-12-31 15:39:42.181 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 1, Status: TXStatus.SUCCESS
2023-12-31 15:39:42.193 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:42 sequence
2023-12-31 15:39:46.897 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:57 sequence
2023-12-31 15:39:48.583 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 28, Status: TXStatus.SUCCESS
2023-12-31 15:39:49.643 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:75 sequence
2023-12-31 15:39:51.300 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:9d sequence
2023-12-31 15:40:01.192 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.prise_tele_chalet_electrical_measurement is taking over 10 seconds
2023-12-31 15:40:02.329 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.prise_tele_salon_electrical_measurement is taking over 10 seconds
2023-12-31 15:40:02.340 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.prise_tele_gym_electrical_measurement is taking over 10 seconds
2023-12-31 15:40:02.346 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.sinope_technologies_sp2610zb_active_power_2 is taking over 10 seconds
2023-12-31 15:40:06.213 WARNING (MainThread) [homeassistant.components.sensor] Updating zha sensor took longer than the scheduled update interval 0:00:30
2023-12-31 15:40:36.213 WARNING (MainThread) [homeassistant.components.sensor] Updating zha sensor took longer than the scheduled update interval 0:00:30
2023-12-31 15:40:36.920 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:27 sequence
2023-12-31 15:40:37.020 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:2e sequence
2023-12-31 15:40:37.025 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 55, Status: TXStatus.SUCCESS
2023-12-31 15:40:38.154 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:44 sequence
2023-12-31 15:40:38.169 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:46 sequence
2023-12-31 15:40:38.185 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:48 sequence
2023-12-31 15:40:38.224 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:50 sequence
2023-12-31 15:40:38.230 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:51 sequence
2023-12-31 15:40:38.249 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 68, Status: TXStatus.NWK_ROUTE_DISCOVERY_FAILED
2023-12-31 15:40:38.266 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:59 sequence
2023-12-31 15:40:38.271 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 68, Status: TXStatus.NWK_ROUTE_DISCOVERY_FAILED
2023-12-31 15:40:38.277 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 68, Status: TXStatus.NWK_ROUTE_DISCOVERY_FAILED
2023-12-31 15:40:38.289 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 68, Status: TXStatus.NWK_ROUTE_DISCOVERY_FAILED
2023-12-31 15:40:38.300 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 68, Status: TXStatus.NWK_ROUTE_DISCOVERY_FAILED
2023-12-31 15:40:38.490 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:6d sequence
2023-12-31 15:40:38.514 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:6f sequence
2023-12-31 15:40:38.715 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:7f sequence
2023-12-31 15:40:40.865 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:a3 sequence
2023-12-31 15:40:41.909 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:a9 sequence
2023-12-31 15:40:41.925 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:aa sequence
2023-12-31 15:40:42.971 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:b1 sequence
2023-12-31 15:40:43.169 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:c0 sequence
2023-12-31 15:40:47.007 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:d3 sequence
2023-12-31 15:40:47.082 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:d8 sequence
2023-12-31 15:40:47.125 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:dc sequence
2023-12-31 15:40:48.160 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 58, Status: TXStatus.NWK_ROUTE_DISCOVERY_FAILED
2023-12-31 15:40:53.163 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.prise_test_puissance is taking over 10 seconds
2023-12-31 15:41:06.213 WARNING (MainThread) [homeassistant.components.sensor] Updating zha sensor took longer than the scheduled update interval 0:00:30
2023-12-31 15:41:08.640 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:3f sequence
2023-12-31 15:41:18.804 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:60 sequence
2023-12-31 15:41:18.839 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 168, Status: TXStatus.SUCCESS
2023-12-31 15:41:18.996 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:6f sequence
2023-12-31 15:41:20.034 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:75 sequence
2023-12-31 15:41:21.072 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:7b sequence
2023-12-31 15:41:32.256 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x6115:1:0x0702]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>')]
2023-12-31 15:41:32.340 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:a8 sequence
2023-12-31 15:41:32.357 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:aa sequence
2023-12-31 15:41:36.215 WARNING (MainThread) [homeassistant.components.sensor] Updating zha sensor took longer than the scheduled update interval 0:00:30
2023-12-31 15:41:38.131 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:ca sequence
2023-12-31 15:41:38.154 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:cd sequence
2023-12-31 15:41:38.163 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x6115:1:0x0b04]: async_initialize: all attempts have failed: [TimeoutError(), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>')]
2023-12-31 15:41:38.284 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 196, Status: TXStatus.SUCCESS
2023-12-31 15:41:39.568 WARNING (MainThread) [zigpy_deconz.api] Duplicate or delayed response for 0x:f3 sequence
2023-12-31 15:41:42.588 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0x6115:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>')]
2023-12-31 15:41:43.203 WARNING (MainThread) [homeassistant.components.zha.core.cluster_handlers] [0xCCCC:1:0x0702]: async_initialize: all attempts have failed: [TimeoutError(), TimeoutError(), TimeoutError(), TimeoutError()]
2023-12-31 15:41:44.532 ERROR (MainThread) [zigpy.zcl] [0x96CF:1:0xff01] Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zigpy/device.py", line 316, in request
    return await req.result
           ^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py", line 377, in request
    return await self._endpoint.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/endpoint.py", line 253, in request
    return await self.device.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/device.py", line 315, in request
    async with asyncio_timeout(timeout):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 518, in write_attributes_safe
    res = await self.write_attributes(attributes, manufacturer=manufacturer)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 83, in wrapper
    with wrap_zigpy_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/src/homeassistant/homeassistant/components/zha/core/cluster_handlers/__init__.py", line 66, in wrap_zigpy_exceptions
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to send request: device did not respond

```

**Comment by puddly** [comment]
@claudegel Try the latest Home Assistant beta. There have been a lot of changes to the Conbee radio library that may help.

**Comment by claudegel** [comment]
I just notice that my Conbee is at firmware 0x264a0700 which is an old one I think. How could I upgrade it to latest firmware in HA

**Comment by claudegel** [comment]
I've flashed the dongle and same result in the log. But since last HA update, 2024.1.1 it's gone. back to normal I hope.

**Comment by claudegel** [comment]
The last HA update fix it. no more error message in log. Thank you
