### ISSUE TITLE
How-to force form network

### ISSUE THREAD

**Issue by pipiche38** [zigpy/zigpy-deconz#186]
when using form_network() when the network is already formed, nothing is done.
What is the process to do that ? I didn't fund any leaveNetwork() as one bellows

**Comment by puddly** [comment]
> when using form_network() when the network is already formed, nothing is done.

Can you double check?  Formation is very fast with the Conbee.

**Comment by pipiche38** [comment]
PanID do not change and all devices remains working

**Comment by puddly** [comment]
Are you using `dev` or https://github.com/zigpy/zigpy-deconz/pull/172?

**Comment by pipiche38** [comment]
dev for now !

**Comment by puddly** [comment]
All work involving network state is happening in #172, which will be merged very soon. I suggest you use it instead of `dev`.

**Comment by pipiche38** [comment]
Oki. When you say merged will happen very soon, what is the timeline ? 
My main issue, is that I cannot develop/integrate something which cannot go for end user, this is why I'm focussing on the current dev, and then I'm doing the update to new-radio-api. 
Now, if the dev for zigpy-deconz is not good enough, I'll indeed work on on the #172 and won't release anything until your PR is merged.

**Comment by pipiche38** [comment]
The form network looks very strange, when using it (with the new-radio-API) the extended PAN Id seems to be taken in consideration, however it looks like teh Trust Center is not reset and the coordinator continue to accept messages from devices previously paired !

In addition we get this stack trace during the force_form 

```
2022-03-15 08:05:25,784 DEBUG   :Command Command.write_parameter (2, <NetworkParameter.aps_designed_coordinator: 9>, b'\x01')
2022-03-15 08:05:25,784 DEBUG   :Send: 0x0b4000090002000901
2022-03-15 08:05:25,792 DEBUG   :Frame received: 0x0b40000800010009
2022-03-15 08:05:25,792 DEBUG   :Write parameter aps_designed_coordinator: SUCCESS
2022-03-15 08:05:25,793 DEBUG   :Command Command.write_parameter (3, <NetworkParameter.nwk_address: 7>, b'\x00\x00')
2022-03-15 08:05:25,793 DEBUG   :Send: 0x0b41000a000300070000
2022-03-15 08:05:25,796 DEBUG   :Frame received: 0x0b41000800010007
2022-03-15 08:05:25,796 DEBUG   :Write parameter nwk_address: SUCCESS
2022-03-15 08:05:25,802 ERROR   :Error Traceback (most recent call last):
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/AppDeconz.py", line 63, in startup
    await super().form_network()
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/zigpy/application.py", line 167, in form_network
    await self.write_network_info(network_info=network_info, node_info=node_info)
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/zigpy_deconz/zigbee/application.py", line 161, in write_network_info
    await self._api.write_parameter(NetworkParameter.mac_address, node_info.ieee)
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/zigpy_deconz/api.py", line 460, in write_parameter
    v = t.serialize(args, NETWORK_PARAMETER_SCHEMA[param])
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/zigpy_deconz/types.py", line 15, in serialize
    return b"".join(t(v).serialize() for t, v in zip(schema, data))
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/zigpy_deconz/types.py", line 15, in <genexpr>
    return b"".join(t(v).serialize() for t, v in zip(schema, data))
TypeError: 'NoneType' object is not iterable

```

**Comment by Hedda** [comment]
Maybe bring @manup from Dresden Elektronik into discussions involving implementation of the new radio API for [zigpy-deconz](https://github.com/zigpy/zigpy-deconz)?

https://github.com/zigpy/zigpy-deconz/pull/172

and

https://github.com/zigpy/zigpy/pull/848

PS: I believe @manup is Dresden Elektronik's lead developer for [deCONZ Serial Protocol](https://github.com/dresden-elektronik/deconz-serial-protocol/) as well as deCONZ firmware for ConBee?

**Comment by pipiche38** [comment]
fixed with recent new-radio-API
