### ISSUE TITLE
Lost communication with every zigbee device on conbee 2

### ISSUE THREAD

**Issue by ahaverty** [zigpy/zigpy-deconz#208]
I've been running ZHA on a conbee 2 via HA for over a year now, but last night every zigbee device lost connectivity.
- Lights
- Motion
- Switches
- All from various manufacturers from Ikea, unk, lumi, ledvance, lidl etc

There was no update done, or any physical changes made to my HA or ZHA.

I've tried rebooting ZHA, restarting home assistant, disconnecting/reconneting my conbee usb.

The only thing that seems to fix for me is individually setting each device back into pairing mode, and adding via Zha again (It remembers the device name/id thankfully).

In terms of related logs, I see:
```
2022-10-19 08:05:25.863 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 196, Status: TXStatus.NWK_ROUTE_DISCOVERY_FAILED
2022-10-19 08:05:31.784 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x5950:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>')]
2022-10-19 08:05:31.799 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x7E37:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>')]
2022-10-19 08:05:31.866 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x9039:1:0x0702]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>')]
2022-10-19 08:05:31.951 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xD15B:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>')]
2022-10-19 08:05:31.960 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xD15B:1:0x0008]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), ControllerException('duplicate 4 TSN'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>')]
2022-10-19 08:05:32.057 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x67BB:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>')]
2022-10-19 08:05:32.069 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0x0E1E:1:0x0300]: async_initialize: all attempts have failed: [DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>'), DeliveryError('Failed to deliver packet: <TXStatus.NWK_ROUTE_DISCOVERY_FAILED: 208>')]
```

and

```
2022-10-19 08:38:12.711 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472475170128] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/zha/api.py", line 1065, in websocket_update_zha_configuration
if not data_to_save[CUSTOM_CONFIGURATION][section]:
KeyError: 'zha_alarm_options'
```

I can see from a previous backup that no ID's or values have changed. zigpy-deconz version has updated this month, but it seems to have been running fine since the 13th Oct - 19th Oct.

Copy of my backup:
```json
{
    "backup_time": "2022-10-19T07:42:29.784030+00:00",
    "network_info": {
        "extended_pan_id": "00:21:2e:ff:ff:07:74:f3",
        "pan_id": "46D3",
        "nwk_update_id": 0,
        "nwk_manager_id": "0000",
        "channel": 15,
        "channel_mask": [
            15
        ],
        "security_level": 5,
        "network_key": {
            "key": "af:ab:fe:0d:6b:5b:2a:6d:37:81:66:2d:53:7a:12:72",
            "tx_counter": 0,
            "rx_counter": 0,
            "seq": 0,
            "partner_ieee": "ff:ff:ff:ff:ff:ff:ff:ff"
        },
        "tc_link_key": {
            "key": "5a:69:67:42:65:65:41:6c:6c:69:61:6e:63:65:30:39",
            "tx_counter": 0,
            "rx_counter": 0,
            "seq": 0,
            "partner_ieee": "00:21:2e:ff:ff:07:74:f3"
        },
        "key_table": [],
        "children": [],
        "nwk_addresses": {},
        "stack_specific": {},
        "metadata": {
            "deconz": {
                "version": 643303168
            }
        },
        "source": "zigpy-deconz@0.19.0"
    },
    "node_info": {
        "nwk": "0000",
        "ieee": "00:21:2e:ff:ff:07:74:f3",
        "logical_type": "coordinator"
    }
}

```

**Comment by puddly** [comment]
I would also recommend upgrading your Conbee's firmware.

**Comment by puddly** [comment]
I'm unfortunately seeing no difference between the two, only a single network configuration has ever been seen by zigpy. After upgrading firmware, have you tried restoring the backup?

**Comment by puddly** [comment]
Restoring from a ZHA backup would reset the radio and re-write the network settings.

The latest firmware is supported. Is your Conbee on a USB 2.0 extension cable? It sometimes gets into a state where it bootloops.

**Comment by puddly** [comment]
Is it still visible from within Windows? Perhaps you can downgrade to the previous version.

**Comment by puddly** [comment]
You generally shouldn't need to reboot anything. Do other USB devices get recognized by your Blue?

**Comment by puddly** [comment]
Try downloading a ZHA backup and then "migrating" by restoring it. If that doesn't work, there's not much else I can think of, unfortunately.

**Comment by puddly** [comment]
Have you tried just rebooting the affected devices, without factory resetting them?

**Comment by puddly** [comment]
Truthfully, this isn't unheard of for the Conbee. I'd get a different Zigbee coordinator (like the CC2652) and utilize the migration feature.

**Comment by puddly** [comment]
I'm not aware of any issues with IKEA devices that are specific to the CC2652. Which ones are you referring to?

**Comment by puddly** [comment]
I'm not aware of any firmware issue that would cause this so it's likely just a tricky device. In any case, if it works now it will work the same way after the migration.

> Mind if I ask what you're running yourself?

I work on the radio libraries so I rotate between the [LAUNCHXL-CC1352P2](https://www.ti.com/tool/LAUNCHXL-CC1352P) (basically the same thing as the CC2652), the Conbee II, and the SkyConnect (EFR32).
