### ISSUE TITLE
Pairing timeout adjustment?

### ISSUE THREAD

**Issue by Dinth** [zigpy/zigpy-deconz#24]
Would it be possible to implement a customizable pairing timeout value in zigpy-deconz? This is present in Deconz software and allowed me to pair all the devices in my house without any problem. Since i migrated to zigpy-deconz (HomeAssistant's ZHA component), i only managed to pair two of my bulbs, pairing of the rest fails with the following:
```
2019-03-03 15:07:47 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 54
2019-03-03 15:07:47 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 55
2019-03-03 15:07:48 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 56
2019-03-03 15:07:53 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 57
2019-03-03 15:07:53 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 97, in request
    r = await asyncio.wait_for(send_fut, SEND_CONFIRM_TIMEOUT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
2019-03-03 15:07:54 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 58
2019-03-03 15:07:54 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 97, in request
    r = await asyncio.wait_for(send_fut, SEND_CONFIRM_TIMEOUT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
2019-03-03 15:07:54 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 59
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 97, in request
    r = await asyncio.wait_for(send_fut, SEND_CONFIRM_TIMEOUT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
2019-03-03 15:07:54 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 60
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 97, in request
    r = await asyncio.wait_for(send_fut, SEND_CONFIRM_TIMEOUT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

**Comment by damarco** [comment]
You can adjust the pairing timeout when calling the service zha.permit from HA, but I do not see how that would make a difference. Please also try with the latest HA version.

**Comment by Dinth** [comment]
> but I do not see how that would make a difference

at least with Deconz, adjusting discovery timeout helps *a lot* when pairing Tradfri lights and the Zigbee antenna cannot be moved close to the bulb

**Comment by dmulcahey** [comment]
@damarco the timeout in question is hard coded in zigpy_deconz.

**Comment by damarco** [comment]
@dmulcahey Which one are you referring to? It should be 60s by default but can be up to 254s ([code](https://github.com/zigpy/zigpy-deconz/blob/24e9225e732bd67ad74f14943129c724fd7b89c6/zigpy_deconz/zigbee/application.py#L127)).

**Comment by damarco** [comment]
@Dinth any update on this?
