### ISSUE TITLE
File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 90, in request     expect_reply=expect_reply,

### ISSUE THREAD

**Issue by vinmar1** [zigpy/zigpy-deconz#25]
Platform
Intel NUC - Ubuntu 18.04.2 LTS - Docker (current) - Hassio 0.90.1
Conbee USB firmware 26320500 using native ZHA integration not deCONZ

Only Samsung motion sensors and Cree bulbs are integrated

Last working 0.89.2

see also #22292 in home-assistant/home-assistant

File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 90, in request
    expect_reply=expect_reply,
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 83, in request
    assert sequence not in self._pending

I happened to save the log it is 151k so I zipped it down to 10k. Wow just caught me i just now shutdown to turn off debug logging and nuke the log because of the size, I didn't know if it impacted performance.

[home-assistant.zip](https://github.com/zigpy/zigpy-deconz/files/3003642/home-assistant.zip)

Also had these errors on the restart but debug is off so this is all I have...

19-03-25 09:51:45 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe9
2019-03-25 09:51:45 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 5, Status: 0x00, 5
2019-03-25 09:51:45 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 6, Status: 0x00, 6
2019-03-25 09:51:45 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 8, Status: 0x00, 8
2019-03-25 09:51:59 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 5
2019-03-25 09:51:59 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 6
2019-03-25 09:51:59 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 8
2019-03-25 09:53:02 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xd0

**Comment by stephenfsnow** [comment]
I think I might be experiencing the same issue using Home Assistant ZHA component... Mainly this seems to prevent control of the lights especially when toggling on/off or changing brightness. To change on/off state or brightness I have to repeat the action in the UI several times before the bulb responds.

Hassio 0.90.2
Raspbee firmware 262F0500

Mix of Osram Lightify RGBW bulbs, recessed lights and light strips
Philips Hue outdoor light strips
Philips Hue Play lights

This is what I get from the logs at startup....

```
2019-03-27 14:23:49 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback <bound method SerialTransport._read_ready of SerialTransport(<uvloop.Loop running=True closed=False debug=False>, <zigpy_deconz.uart.Gateway object at 0x7339ff30>, Serial<id=0x758fd890, open=True>(port='/dev/ttyAMA0', baudrate=38400, bytesize=8, parity='N', stopbits=1, timeout=0, xonxoff=False, rtscts=False, dsrdtr=False))>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 62, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.7/site-packages/serial_asyncio/__init__.py", line 106, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/uart.py", line 63, in data_received
    self._api.data_received(frame)
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/api.py", line 162, in data_received
    getattr(self, '_handle_%s' % (command, ))(data)
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/api.py", line 251, in _handle_aps_data_indication
    data[16])   # rssi
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 169, in handle_rx
    dst_ep, tsn, command_id, args)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/zha/__init__.py", line 164, in handle_message
    is_reply, profile, cluster, src_ep, dst_ep, tsn, command_id, args)
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 111, in handle_message
    return endpoint.handle_message(is_reply, profile, cluster, tsn, command_id, args)
  File "/usr/local/lib/python3.7/site-packages/zigpy/zdo/__init__.py", line 66, in handle_message
    self.reply(0x8001, 0, app.ieee, app.nwk, 0, 0, [])
  File "/usr/local/lib/python3.7/site-packages/zigpy/zdo/__init__.py", line 49, in reply
    sequence, data = self._serialize(command, *args)
  File "/usr/local/lib/python3.7/site-packages/zigpy/zdo/__init__.py", line 23, in _serialize
    data += t.serialize(args, schema)
  File "/usr/local/lib/python3.7/site-packages/zigpy/types/__init__.py", line 15, in serialize
    return b''.join(t(v).serialize() for t, v in zip(schema, data))
  File "/usr/local/lib/python3.7/site-packages/zigpy/types/__init__.py", line 15, in <genexpr>
    return b''.join(t(v).serialize() for t, v in zip(schema, data))
TypeError: 'NoneType' object is not iterable
2019-03-27 14:23:50 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe9
2019-03-27 14:23:50 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe9
2019-03-27 14:23:50 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe9
2019-03-27 14:23:50 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe9
2019-03-27 14:23:50 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe9
2019-03-27 14:23:50 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe9
2019-03-27 14:23:50 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe9
2019-03-27 14:23:52 WARNING (MainThread) [zigpy.zdo] Unknown ZDO cluster 0x8038
2019-03-27 14:23:52 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected response TSN=0 command=32824 args=b'\x00\x00\xf8\xff\x07\x1a\x00\x07\x00\x10\xa6\xb4\xa0\x9f\xbd\xc8\xa0\xc6\xc1\xbb\x9f\xab\xc0\x9f\xa0\xc0', 0
2019-03-27 14:24:04 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 4
2019-03-27 14:24:05 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 5
2019-03-27 14:24:05 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 6
2019-03-27 14:24:05 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 7
2019-03-27 14:24:05 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 8
2019-03-27 14:24:05 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 9
2019-03-27 14:24:05 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 10
2019-03-27 14:24:05 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 11
2019-03-27 14:24:05 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 12
2019-03-27 14:24:05 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 13
2019-03-27 14:24:05 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 14
2019-03-27 14:24:05 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 15
2019-03-27 14:24:05 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 16
2019-03-27 14:24:06 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 17
2019-03-27 14:24:06 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 18
2019-03-27 14:24:06 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 20
2019-03-27 14:24:06 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 21
2019-03-27 14:24:06 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 22
2019-03-27 14:24:06 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 23
2019-03-27 14:24:06 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 27
2019-03-27 14:24:06 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 36
2019-03-27 14:24:06 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 39
2019-03-27 14:24:08 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe9
2019-03-27 14:24:08 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe9
2019-03-27 14:24:08 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 80, Status: 0x00, 80
2019-03-27 14:24:08 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 83, Status: 0x00, 83
2019-03-27 14:24:08 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe9
2019-03-27 14:24:08 WARNING (MainThread) [zigpy_deconz.zigbee.application] Unexpected transmit confirm for request id 86, Status: 0x00, 86
2019-03-27 14:24:17 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of platform zha is taking over 10 seconds.
2019-03-27 14:24:17 WARNING (MainThread) [homeassistant.components.light] Setup of platform zha is taking over 10 seconds.
2019-03-27 14:24:17 WARNING (MainThread) [homeassistant.components.sensor] Setup of platform zha is taking over 10 seconds.
2019-03-27 14:24:17 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xd0
2019-03-27 14:24:18 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xd0
2019-03-27 14:24:18 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xd0
2019-03-27 14:24:18 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xd0
2019-03-27 14:24:18 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xd0
2019-03-27 14:24:18 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xd0
2019-03-27 14:24:22 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 68
2019-03-27 14:24:22 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 73
2019-03-27 14:24:22 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 80
2019-03-27 14:24:22 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 83
2019-03-27 14:24:23 WARNING (MainThread) [zigpy_deconz.zigbee.application] Failed to receive transmit confirm for request id: 86
```

And then whenever attempting to turn a light on/off or adjust brightness:


```
2019-03-27 14:49:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1842488304] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/light/__init__.py", line 285, in async_handle_light_on_service
    await light.async_turn_on(**pars)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/zha/light.py", line 195, in async_turn_on
    success = await self._on_off_channel.on()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/zha/core/channels/__init__.py", line 53, in wrapper
    result = await command(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 90, in request
    expect_reply=expect_reply,
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 83, in request
    assert sequence not in self._pending
AssertionError
2019-03-27 14:49:25 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1842488304] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/light/__init__.py", line 285, in async_handle_light_on_service
    await light.async_turn_on(**pars)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/zha/light.py", line 195, in async_turn_on
    success = await self._on_off_channel.on()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/zha/core/channels/__init__.py", line 53, in wrapper
    result = await command(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 90, in request
    expect_reply=expect_reply,
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 83, in request
    assert sequence not in self._pending
AssertionError
2019-03-27 14:49:35 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1842488304] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/light/__init__.py", line 285, in async_handle_light_on_service
    await light.async_turn_on(**pars)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/zha/light.py", line 186, in async_turn_on
    duration
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/zha/core/channels/__init__.py", line 53, in wrapper
    result = await command(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 90, in request
    expect_reply=expect_reply,
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 83, in request
    assert sequence not in self._pending
AssertionError
```

**Comment by Adminiuga** [comment]
@stephenfsnow Yep, looks like the same issue. And I think this exception is causing a leaked TSN
```
2019-03-27 14:23:49 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback <bound method SerialTransport._read_ready of SerialTransport(<uvloop.Loop running=True closed=False debug=False>, <zigpy_deconz.uart.Gateway object at 0x7339ff30>, Serial<id=0x758fd890, open=True>(port='/dev/ttyAMA0', baudrate=38400, bytesize=8, parity='N', stopbits=1, timeout=0, xonxoff=False, rtscts=False, dsrdtr=False))>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 62, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.7/site-packages/serial_asyncio/__init__.py", line 106, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/uart.py", line 63, in data_received
    self._api.data_received(frame)
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/api.py", line 162, in data_received
    getattr(self, '_handle_%s' % (command, ))(data)
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/api.py", line 251, in _handle_aps_data_indication
    data[16])   # rssi
  File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 169, in handle_rx
    dst_ep, tsn, command_id, args)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/zha/__init__.py", line 164, in handle_message
    is_reply, profile, cluster, src_ep, dst_ep, tsn, command_id, args)
  File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 111, in handle_message
    return endpoint.handle_message(is_reply, profile, cluster, tsn, command_id, args)
  File "/usr/local/lib/python3.7/site-packages/zigpy/zdo/__init__.py", line 66, in handle_message
    self.reply(0x8001, 0, app.ieee, app.nwk, 0, 0, [])
  File "/usr/local/lib/python3.7/site-packages/zigpy/zdo/__init__.py", line 49, in reply
    sequence, data = self._serialize(command, *args)
  File "/usr/local/lib/python3.7/site-packages/zigpy/zdo/__init__.py", line 23, in _serialize
    data += t.serialize(args, schema)
  File "/usr/local/lib/python3.7/site-packages/zigpy/types/__init__.py", line 15, in serialize
    return b''.join(t(v).serialize() for t, v in zip(schema, data))
  File "/usr/local/lib/python3.7/site-packages/zigpy/types/__init__.py", line 15, in <genexpr>
    return b''.join(t(v).serialize() for t, v in zip(schema, data))
TypeError: 'NoneType' object is not iterable
```

**Comment by stephenfsnow** [comment]
FWIW, I downgraded Home Assistant from 0.90.2 to 0.89.2 and lights are responsive again (mostly). I still see repeats of `Error while sending frame: 0xe9` and `Error while sending frame: 0xd0` from time to time and the AssertionError from before just not as consistently.

**Comment by Adminiuga** [comment]
IMO two issues are at play here and one is exacerbating the other.
1. in 0.89.2 ZHA device polling wasn't working
2. I think in certain scenarios zigpy_deconz is leaking TSN

Since 0.90.1 had fixed ZHA device polling, there's more data requested from the devices, thus increasing the chances for  the 2nd issue to occur

@stephenfsnow do you still have the original log you posted here? I'd like to see a few lines preceeding 
```
2019-03-27 14:23:49 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback <bound method SerialTransport._read_ready of SerialTransport(<uvloop.Loop running=True closed=False debug=False>, <zigpy_deconz.uart.Gateway object at 0x7339ff30>, Serial<id=0x758fd890, open=True>(port='/dev/ttyAMA0', baudrate=38400, bytesize=8, parity='N', stopbits=1, timeout=0, xonxoff=False, rtscts=False, dsrdtr=False))>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 62, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.7/site-packages/serial_asyncio/__init__.py", line 106, in _read_ready
    self._protocol.data_received(data)
```
line. I'd like to see what data you actually got from UART before it threw.

**Comment by stephenfsnow** [comment]
@Adminiuga Unfortunately I do not but I'm about to go back to 0.90.2 (I'll just switch back and suffer through the deConz add-on not being able to set color temperature on my OSRAM Lightify lights) and then I will attempt to recreate the errors. I'll upload the full log once I have it.

BTW I really appreciate the work on this. I was amazed to see how well it worked with my OSRAM RGBW lights and setting color temperature. I've consistently had color temp issues with my OSRAM RGBW lights while using the deCONZ Rest API. I suspect it's because I'm stuck with the ZHA version of the bulbs (being in the US and unable to upgrade firmware) and that dev team is probably focused on the ZLL version of the same products.

I have a good variety of OSRAM Lightify (US version, prior to LEDVANCE switchover) light products as well as a bunch of the 4 button Lightify remotes. I noticed there's some work elsewhere to get those integrated so I'd love to help test with any of my Lightify products where I can.

**Comment by vinmar1** [comment]
Here is something that does not seem to make sense to me but Adminiuga it may to you...
I went back to 0.89.2 because it was more stable for my Samjin Sensors and Cree bulbs.

Only real issue on 0.89.2 was anytime I re-started Hassio my cree bulbs would be offline. If I powered them off for a minute and then back on they would register and worked pretty good. Occasionally one would not turn on/off but rarely. I would also get an occasional error but ignored it.

This last time I restarted the system all 3 cree bulbs were offline as usual. I was busy and did not go reset them. About an hour or so later I checked the UI and they all came back online on their own. I have had no errors at all this time other than a couple at startup and all that changed is I did not manually reset the bulbs I let them come back on their own.

The errors at startup were the usual...

019-03-28 08:29:17 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe9
019-03-28 08:29:17 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xf0
2019-03-28 08:29:17 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xe1

I don't have debug logging turned on but those are the common errors I would occasionally get which I assume means the system cannot communicate with the bulbs.

**Comment by damarco** [comment]
@vinmar1 Can you try firmware 262f0500 and the latest HA beta? Please also turn on debug logging for zigpy-deconz and zigpy. If there are still issues please share the log and the exact devices you have added.

**Comment by vinmar1** [comment]
Downgrading the firmware to 262f0500 from 26320500 that went without a problem. I have turned on debug logging again.

I have never run a beta version, I turned on the beta channel for Hass.io Supervisor and updated there to 151 but need to know what command to run when I SSH in to get the beta HA version installed..

**Comment by vinmar1** [comment]
I did get at least this far while waiting for beta install instructions...

Firmware as stated above is now at 262f0500
HA is at 090.2

I started a new log file so this is from a fresh boot up. One thing I have found is if I turn my Cree bulbs on before a reboot the system appears to always find them, I just go in and turn them off after.

[home-assistant.log](https://github.com/zigpy/zigpy-deconz/files/3025980/home-assistant.log)

**Comment by damarco** [comment]
I assume you are running hassio. Can you try this:

`hassio homeassistant update --version=0.91.0.b3`

> One thing I have found is if I turn my Cree bulbs on before a reboot the system appears to always find them, I just go in and turn them off after.

What happens if the Cree bulbs are turned off (but still powered) and then HA is restarted?

**Comment by vinmar1** [comment]
I tried hassio homeassistant update --version=0.91.0.b3 from a prompt in HA but it just gave me an error.

I am running in Docker with Portainer... I was able to download an image I see it in Portainer using "sudo docker pull homeassistant/home-assistant:rc" from a prompt in Ubuntu but I don't know how to apply it.

If the Cree bulbs are powered but not illuminated they usually don't come online until I power them off and then on. Occasionally they come online but after 30 to 60 minutes. If I have them illuminated it seems they are always immediately recognized.

**Comment by dmulcahey** [comment]
The beta will fix that. Ask on the hassio channel for assistance

**Comment by damarco** [comment]
Are you running hassio or HA as a container?

**Comment by vinmar1** [comment]
I'm running hassio... this is what my Portainer looks like

![HA](https://user-images.githubusercontent.com/47003880/55291879-01250c00-53b2-11e9-8215-71f494a0e750.jpg)

**Comment by vinmar1** [comment]
I am now on the Beta Version 0.91.0b3

**Comment by vinmar1** [comment]
Okay finally got the beta up and running...

Beta 0.91.0b3 and ConBee firmware 262f0500 using native ZHA...

NO ERRORS YET! Here is the logfile from startup. I let a full cycle run with motion sensors triggering automations turning lights on and off run before copying it.

[home-assistant.zip](https://github.com/zigpy/zigpy-deconz/files/3027348/home-assistant.zip)

The only thing maybe worth mentioning, not that it makes any real difference is I had the ConBee on firmware 26300500 because of an issue some time back and was then advised to go to that version. I looked for the thread but could not find it. The version I am on now is where I started originally.

**Comment by dmulcahey** [comment]
Glad to hear you’re up and running

**Comment by vinmar1** [comment]
Thanks Dave... 

I've pushed in the 0.91.0b4 update in and I have to say everything is fabulous... the current beta has not only seemed to cure this issue but other small annoyances from other entities as well. I'll keep you all posted if anything changes.

**Comment by vinmar1** [comment]
Kudo's to you all... what I know about writing code could be written on the head of a pin and it's the phone number of someone that does know how. I'm an infrastructure guy learning more than I thought I would want to about software and appreciate all of your talents in making this a great product.

In my opinion this really heightens the versatility of HA. I was on a HUSBZB-1 on my Pi and while it was really good when  I went to the NUC decided to split the functionality in to an Aeotec and the ConBee figuring the longer range support for both would be there. I also didn't want to run deCONZ so seeing the native ZHA availability for ConBee with the deCONZ communication protocol seemed to be the way to go.

It's you guys that are making this all possible and for that a huge thanks!!!!

**Comment by vinmar1** [comment]
New problem... Beta 0.91.0b5 but it may have happened on b4.

Samjin motion sensors occasionally "get stuck on". I tried using the states tool to force it off but it just pops back to on in the GUI. There is no error message coming up but I pulled a copy of the log anyway.

[home-assistant.zip](https://github.com/zigpy/zigpy-deconz/files/3036296/home-assistant.zip)

**Comment by vinmar1** [comment]
Looks like all is good on 0.91.0 other than a few warnings at startup as noted below so I am closing this ticket.

Here is the info on the warnings from a clean start if you want it.

No response to aps_data_request command
7:43 AM components/zha/core/helpers.py (WARNING)
Failed to receive transmit confirm for request id: 9
7:43 AM components/zha/core/helpers.py (WARNING)
Failed to receive transmit confirm for request id: 8
7:43 AM components/zha/core/helpers.py (WARNING)
Error while sending frame: 0xe9
7:42 AM components/zha/core/helpers.py (WARNING)

Here is the log if you want to take a look... it's small

[home-assistant.zip](https://github.com/zigpy/zigpy-deconz/files/3043292/home-assistant.zip)
