### ISSUE TITLE
cant initialize Conbee in HA

### ISSUE THREAD

**Issue by llonca13** [zigpy/zigpy-deconz#38]
hass.io/odroidC2/conbee1/latestFW/latestHA

I cant initialize ConBee in HA, get this error:

Error setting up entry /dev/ttyUSB0 for zha
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/config_entries.py", line 309, in async_setup
    hass, self)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/zha/__init__.py", line 99, in async_setup_entry
    await zha_gateway.async_initialize(config_entry)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/zha/core/gateway.py", line 90, in async_initialize
    await self.application_controller.startup(auto_form=True)
  File "/usr/local/lib/python3.7/site-packages/bellows/zigbee/application.py", line 102, in startup
    await self.initialize()
  File "/usr/local/lib/python3.7/site-packages/bellows/zigbee/application.py", line 53, in initialize
    await e.reset()
  File "/usr/local/lib/python3.7/site-packages/bellows/ezsp.py", line 54, in reset
    await self._gw.reset()
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by Adminiuga** [comment]
When configuring integration, select `Deconz` radio type and not EZSP

**Comment by llonca13** [comment]
Thank you for quick reply. I did see ezsp.py used and was confused because i did specify deconz:

zha:
  usb_path: /dev/ttyUSB0
  database_path: /config/zigbee.db
  radio_type: deconz

What else can I try?

**Comment by llonca13** [comment]
Maybe name of the variable **radio_type** changed recently?

**Comment by Adminiuga** [comment]
remove it from the configuration file and configure it through config panel -> integrations -> zha
I don't think name for the deconz radio changed recently. But try configuration through integration 1st.

**Comment by Adminiuga** [comment]
And make sure you delete any existing ZHA integrations 1st, AFAIK it may ignore changes to `configuration.yaml`  once it imported it into a  config_entry.

**Comment by llonca13** [comment]
Thank you. After deleting zha: in config (and deleting zigbee.db file), and adding zha integration through web gui, it works :)

Thank you, closed
