### ISSUE TITLE
unable to pair Aqara Door/Window Sensor (v1)

### ISSUE THREAD

**Issue by ErnstEeldert** [zigpy/zigpy-deconz#46]
I am running Home Assistant 0.94.3 with the ZHA component wired up to a Conbee (latest firmware).

Everything is working as expected, however, I have one sensor which I am unable to pair. This sensor is known good as it pairs and works with deconz directly just fine.

Is this because the v1 sensor is not supported? If so, would it be hard to add support?

Anyways, here are the logs from the pairing dance:

 2019-06-16 19:33:50 INFO (MainThread) [zigpy_deconz.zigbee.application] New device joined: 0xedca, 00:15:8d:00:02:24:9f:41
 2019-06-16 19:33:50 INFO (MainThread) [zigpy.application] Device 0xedca (00:15:8d:00:02:24:9f:41) joined the network
 2019-06-16 19:33:50 INFO (MainThread) [zigpy.device] [0xedca] Requesting 'Node Descriptor'
 Tries remaining: 2
 2019-06-16 19:33:50 INFO (MainThread) [zigpy.device] [0xedca] Requesting 'Node Descriptor'
 Tries remaining: 2
 2019-06-16 19:33:57 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xf0
 2019-06-16 19:33:57 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xf0
 Tries remaining: 1
 Tries remaining: 1
 2019-06-16 19:34:16 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xf0
 2019-06-16 19:34:16 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xf0
 2019-06-16 19:34:26 WARNING (MainThread) [zigpy.device] [0xedca] Requesting Node Descriptor failed: 
 2019-06-16 19:34:26 WARNING (MainThread) [zigpy.device] [0xedca] Requesting Node Descriptor failed: 
 2019-06-16 19:34:26 INFO (MainThread) [zigpy.device] [0xedca] Discovering endpoints
 Tries remaining: 3
 2019-06-16 19:34:30 INFO (Thread-36) [pyhap.hap_server] 192.168.1.102 - "PUT /characteristics HTTP/1.1" 204 -
 2019-06-16 19:34:30 INFO (Thread-36) [pyhap.hap_server] 192.168.1.102 - "PUT /characteristics HTTP/1.1" 204 -
 2019-06-16 19:34:30 INFO (Thread-36) [pyhap.hap_server] 192.168.1.102 - "GET /characteristics?id=523764952.10,523764952.9,4129822414.9,4129822414.10 HTTP/1.1" 207 -
 2019-06-16 19:34:34 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xf0
 2019-06-16 19:34:39 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.2943566416] Connection closed by client
 2019-06-16 19:34:41 INFO (Thread-4) [pyhap.hap_server] 192.168.1.107 - "PUT /characteristics HTTP/1.1" 204 -
 2019-06-16 19:34:41 INFO (Thread-4) [pyhap.hap_server] 192.168.1.107 - "PUT /characteristics HTTP/1.1" 204 -
 Tries remaining: 2
 2019-06-16 19:34:53 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xf0
 Tries remaining: 1
 2019-06-16 19:35:13 WARNING (MainThread) [zigpy_deconz.zigbee.application] Error while sending frame: 0xf0
 2019-06-16 19:35:23 ERROR (MainThread) [zigpy.device] Failed ZDO request during device initialization: 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 76, in _initialize
     epr = await self.zdo.request(0x0005, self.nwk, tries=3, delay=2)
   File "/usr/local/lib/python3.7/site-packages/zigpy/util.py", line 53, in retry
     r = await func()
   File "/usr/local/lib/python3.7/site-packages/zigpy/device.py", line 129, in request
     expect_reply=expect_reply,
   File "/usr/local/lib/python3.7/site-packages/zigpy_deconz/zigbee/application.py", line 120, in request
     return await asyncio.wait_for(reply_fut, timeout)
   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
     raise futures.TimeoutError()
 concurrent.futures._base.TimeoutError

**Comment by Adminiuga** [comment]
can you also enable `zigpy_deconz.uart: debug` logging? I'd like to see the actual frames exchanged with the ConBee. 

`Error while sending frame: 0xf0` -- this status means the child did not poll its parent for new data. When pairing, do you keep pressing the button every 1.5s to keep the device alive?

**Comment by ErnstEeldert** [comment]
Solved, paired like a charm when pressing the button every 1.5s. Thanks for the quick response!

I still captured the logs on a failed pair attempt here: https://hastebin.com/esiyonaqem.cs

In this case, the magnet was moved to the sensor a couple of times.
